# Generated by Django 4.2.19 on 2025-03-03 04:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.RenameField(
            model_name='guestfeedback',
            old_name='submission_date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='guestfeedback',
            name='amenities_rating',
        ),
        migrations.RemoveField(
            model_name='guestfeedback',
            name='complaint_response',
        ),
        migrations.RemoveField(
            model_name='guestfeedback',
            name='food_presentation',
        ),
        migrations.RemoveField(
            model_name='guestfeedback',
            name='food_temperature',
        ),
        migrations.RemoveField(
            model_name='guestfeedback',
            name='hotel_cleanliness',
        ),
        migrations.RemoveField(
            model_name='guestfeedback',
            name='housekeeping',
        ),
        migrations.RemoveField(
            model_name='guestfeedback',
            name='portion_size',
        ),
        migrations.RemoveField(
            model_name='guestfeedback',
            name='reception_rating',
        ),
        migrations.RemoveField(
            model_name='guestfeedback',
            name='restaurant_ambience',
        ),
        migrations.RemoveField(
            model_name='guestfeedback',
            name='restaurant_setup',
        ),
        migrations.RemoveField(
            model_name='guestfeedback',
            name='room_cleanliness',
        ),
        migrations.RemoveField(
            model_name='guestfeedback',
            name='room_service',
        ),
        migrations.RemoveField(
            model_name='guestfeedback',
            name='staff_recommendation',
        ),
        migrations.RemoveField(
            model_name='guestfeedback',
            name='toilet_cleanliness',
        ),
        migrations.RemoveField(
            model_name='guestfeedback',
            name='value_money',
        ),
        migrations.RemoveField(
            model_name='guestfeedback',
            name='waiting_team',
        ),
        migrations.RemoveField(
            model_name='guestfeedback',
            name='waiting_time',
        ),
        migrations.RemoveField(
            model_name='guestfeedback',
            name='welcome_rating',
        ),
        migrations.AddField(
            model_name='guestfeedback',
            name='room_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='guestfeedback',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comments.ratingcategory')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='comments.guestfeedback')),
            ],
        ),
    ]
